apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bgbye-data-pvc
  namespace: bgbye
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  # storageClassName: standard  # uncomment if needed