apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bgbye-ui-ingress
  namespace: bgbye
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: bgbye.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bgbye-ui-svc
                port:
                  number: 80